/* Admin authentication, seed action, and compact collection editor. */
import { auth, db } from './firebase.js';
import { signInWithEmailAndPassword, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, orderBy, query, serverTimestamp, updateDoc, writeBatch } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
const adminEmail='victoribitoye70@gmail.com', here=location.pathname.split('/').pop(), isLogin=here==='login.html';
const mustBeAdmin=user=>!!user&&user.email===adminEmail;
onAuthStateChanged(auth,user=>{if(isLogin&&mustBeAdmin(user))location.href='index.html';if(!isLogin&&!mustBeAdmin(user))location.href='login.html';});
document.querySelector('#login-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),s=document.querySelector('#login-status');try{await signInWithEmailAndPassword(auth,f.get('email'),f.get('password'));s.textContent='Signed in.'}catch(error){console.error(error);s.textContent=`Sign-in failed: ${error.code || 'unknown-error'}`}});
document.querySelector('#logout')?.addEventListener('click',()=>signOut(auth));
const samples={events:Array.from({length:20},(_,i)=>({title:`Campus event ${i+1}`,date:`2026-${String(10+Math.floor(i/5)).padStart(2,'0')}-${String((i%5)*5+3).padStart(2,'0')}`,time:'10:00 AM',category:['Term dates','Holidays','Exams','Sports','Events'][i%5],description:'A fictional Ladex 2026/2027 session activity.'})),staff:Array.from({length:12},(_,i)=>({name:`Dr. ${['Ada Bello','Tunde Akin','Mariam Yusuf','Chidi Okafor'][i%4]} ${i+1}`,role:['Lecturer','Senior Lecturer','Programme Coordinator'][i%3],faculty:['Computing & Technology','Management & Social Sciences','Natural & Applied Sciences'][i%3],bio:'A fictional Ladex educator committed to student learning.'})),news:Array.from({length:8},(_,i)=>({title:`Ladex campus update ${i+1}`,date:`2026-09-${String(24-i).padStart(2,'0')}`,category:['Campus life','Academics','Community'][i%3],image:i<3?`news-${i+1}.jpg`:'',summary:'A short fictional campus-news summary.',body:'This is a fictional full news article created for the Ladex website demonstration.'})),notices:[{title:'Admissions update',message:'Applications are open for the fictional 2026/2027 session.',active:true},{title:'Library hours',message:'The library opens from 8:00 AM to 8:00 PM on weekdays.',active:true},{title:'Campus safety',message:'Please carry your student identity card while on campus.',active:true}]};
document.querySelector('#seed-data')?.addEventListener('click',async e=>{e.currentTarget.disabled=true;const s=document.querySelector('#seed-status');try{const batch=writeBatch(db);Object.entries(samples).forEach(([col,rows])=>rows.forEach(row=>batch.set(doc(collection(db,col)),row)));await batch.commit();s.textContent='Sample data loaded successfully.'}catch{ s.textContent='Could not load data. Confirm your admin login and Firestore rules.'}finally{e.currentTarget.disabled=false}});
const fields={events:['title','date','time','category','description'],staff:['name','role','faculty','bio'],news:['title','date','category','image','summary','body'],notices:['title','message','active']};let current='events';
const safe=v=>String(v??'');function formFor(item={}){const box=document.querySelector('#admin-form');box.replaceChildren();if(current==='messages')return;const form=document.createElement('form');form.className='contact-form';fields[current].forEach(key=>{const l=document.createElement('label');l.textContent=key;let input=key==='body'||key==='description'||key==='bio'||key==='message'?document.createElement('textarea'):document.createElement('input');input.name=key;input.value=safe(item[key]);if(key==='date')input.type='date';if(key==='active'){input.type='checkbox';input.checked=item[key]!==false}l.append(input);form.append(l)});const save=document.createElement('button');save.className='button button-gold';save.textContent='Save';form.append(save);form.onsubmit=async e=>{e.preventDefault();save.disabled=true;const data={};fields[current].forEach(k=>{const x=form.elements[k];data[k]=k==='active'?x.checked:x.value.trim()});try{item.id?await updateDoc(doc(db,current,item.id),data):await addDoc(collection(db,current),data);box.replaceChildren();list()}finally{save.disabled=false}};box.append(form)}
async function list(){const target=document.querySelector('#admin-list');if(!target)return;target.textContent='Loading…';try{const snap=await getDocs(query(collection(db,current),...(current==='messages'?[orderBy('createdAt','desc')]:[])));target.replaceChildren();if(snap.empty){target.textContent='No records yet.';return}snap.docs.forEach(d=>{const data=d.data(),row=document.createElement('article');row.className='admin-row';const title=document.createElement('strong');title.textContent=safe(data.title||data.name||data.subject||'Message');const summary=document.createElement('p');summary.textContent=safe(data.message||data.description||data.role||data.summary||'');const del=document.createElement('button');del.textContent='Delete';del.onclick=async()=>{if(confirm('Delete this item?')){await deleteDoc(doc(db,current,d.id));list()}};row.append(title,summary);if(current!=='messages'){const edit=document.createElement('button');edit.textContent='Edit';edit.onclick=()=>formFor({id:d.id,...data});row.append(edit)}row.append(del);target.append(row)})}catch{target.textContent='Could not load records. Check rules and indexes.'}}
document.querySelectorAll('.admin-tabs button').forEach(b=>b.onclick=()=>{current=b.dataset.collection;document.querySelector('#admin-title').textContent=current[0].toUpperCase()+current.slice(1);document.querySelector('#new-item').hidden=current==='messages';document.querySelector('#admin-form').replaceChildren();list()});document.querySelector('#new-item')?.addEventListener('click',()=>formFor());if(document.querySelector('#admin-list'))list();
const applicationStatuses=['new','reviewing','admitted','rejected'];
const applicationDate=value=>{const date=value?.toDate?value.toDate():new Date(value);return Number.isNaN(date?.getTime())?'Date pending':new Intl.DateTimeFormat('en-NG',{day:'numeric',month:'short',year:'numeric'}).format(date)};
const applicationValue=(label,value)=>{const row=document.createElement('p'),name=document.createElement('strong');name.textContent=`${label}: `;row.append(name,document.createTextNode(value||'—'));return row};
async function openApplication(id){const target=document.querySelector('#application-details');if(!target)return;target.textContent='Loading application…';try{const snap=await getDoc(doc(db,'applications',id));if(!snap.exists()){target.textContent='Application not found.';return}const application=snap.data();target.replaceChildren();target.append(applicationValue('Reference number',application.reference),applicationValue('Full name',application.fullName),applicationValue('Email',application.email),applicationValue('Phone',application.phone),applicationValue('Date of birth',application.dateOfBirth),applicationValue('Programme',application.programme),applicationValue('Last school',application.lastSchool),applicationValue('Personal statement',application.statement),applicationValue('Submitted',applicationDate(application.createdAt)));const studentIdLabel=document.createElement('label'),studentId=document.createElement('input');studentIdLabel.textContent='Student ID';studentId.value=safe(application.studentId);studentIdLabel.append(studentId);const label=document.createElement('label');label.textContent='Status';const select=document.createElement('select');applicationStatuses.forEach(status=>{const option=document.createElement('option');option.value=status;option.textContent=status;option.selected=status===(application.status||'new');select.append(option)});label.append(select);const save=document.createElement('button');save.textContent='Save changes';save.onclick=async()=>{save.disabled=true;try{await updateDoc(doc(db,'applications',id),{status:select.value,studentId:studentId.value.trim()});await listApplications()}finally{save.disabled=false}};const remove=document.createElement('button');remove.textContent='Delete';remove.onclick=async()=>{if(confirm('Delete this application?')){await deleteDoc(doc(db,'applications',id));target.replaceChildren();await listApplications()}};target.append(studentIdLabel,label,save,remove)}catch{target.textContent='Could not load this application.'}}
async function listApplications(){const target=document.querySelector('#applications-list');if(!target)return;target.textContent='Loading applications…';try{const snap=await getDocs(query(collection(db,'applications'),orderBy('createdAt','desc')));target.replaceChildren();if(snap.empty){target.textContent='No applications yet.';return}snap.docs.forEach(record=>{const application=record.data(),row=document.createElement('article'),name=document.createElement('strong'),summary=document.createElement('p'),open=document.createElement('button');row.className='admin-row';name.textContent=application.fullName||'Application';summary.textContent=`${application.reference||'Reference pending'} · ${application.programme||'Programme not provided'} · ${applicationDate(application.createdAt)} · ${application.status||'new'}${application.studentId?` · Student ID: ${application.studentId}`:''}`;open.textContent='Open';open.onclick=()=>openApplication(record.id);row.append(name,summary,open);target.append(row)})}catch{target.textContent='Could not load applications. Check rules and indexes.'}}
if(document.querySelector('#applications-list'))listApplications();
