/* Shared layout loader and lightweight interactive components. */
const loadPartial = async (target, path) => { try { const response = await fetch(path); if (!response.ok) throw new Error(); document.querySelector(target).innerHTML = await response.text(); } catch { document.querySelector(target).innerHTML = '<p class="layout-error">Navigation could not be loaded.</p>'; } };
const partialPrefix = /\/(?:student|admin)\//.test(location.pathname) ? '../' : '';
Promise.all([loadPartial('#site-header', `${partialPrefix}partials/header.html`), loadPartial('#site-footer', `${partialPrefix}partials/footer.html`)]).then(() => {
  // Keep the shared News destination on the Firestore-powered news archive.
  document.querySelectorAll('a[href="index.html#news"]').forEach(link => link.href = 'news.html');
  if (partialPrefix) document.querySelectorAll('#site-header a[href], #site-footer a[href], #site-header img[src], #site-footer img[src]').forEach(element => { const attribute = element.hasAttribute('href') ? 'href' : 'src', value = element.getAttribute(attribute); if (value && !value.startsWith('#') && !/^(?:[a-z]+:|\/)/i.test(value)) element.setAttribute(attribute, `${partialPrefix}${value}`); });
  const toggle = document.querySelector('.menu-toggle'), nav = document.querySelector('#main-menu');
  toggle?.addEventListener('click', () => { const open = nav.classList.toggle('open'); toggle.setAttribute('aria-expanded', open); toggle.setAttribute('aria-label', open ? 'Close main menu' : 'Open main menu'); });
  document.querySelectorAll('.has-submenu > button').forEach(button => button.addEventListener('click', () => { if (innerWidth < 950) { const item = button.parentElement, open = item.classList.toggle('open'); button.setAttribute('aria-expanded', open); } }));
  document.querySelector('.newsletter')?.addEventListener('submit', event => { event.preventDefault(); event.currentTarget.reset(); alert('Thank you for subscribing to Ladex updates.'); });
});
const slides = [...document.querySelectorAll('.slide')], dots = [...document.querySelectorAll('.slider-dots button')]; let activeSlide = 0, sliderTimer, touchStart = 0;
const showSlide = index => { activeSlide = (index + slides.length) % slides.length; slides.forEach((slide, i) => { const current = i === activeSlide; slide.classList.toggle('is-active', current); slide.setAttribute('aria-hidden', !current); dots[i].classList.toggle('is-active', current); dots[i].setAttribute('aria-selected', current); }); };
const startSlider = () => { if (!matchMedia('(prefers-reduced-motion: reduce)').matches) sliderTimer = setInterval(() => showSlide(activeSlide + 1), 6000); }; const stopSlider = () => clearInterval(sliderTimer);
document.querySelector('.next')?.addEventListener('click', () => showSlide(activeSlide + 1)); document.querySelector('.previous')?.addEventListener('click', () => showSlide(activeSlide - 1)); dots.forEach((dot, i) => dot.addEventListener('click', () => showSlide(i)));
const hero = document.querySelector('.hero'); hero?.addEventListener('mouseenter', stopSlider); hero?.addEventListener('mouseleave', startSlider); hero?.addEventListener('touchstart', e => touchStart = e.changedTouches[0].screenX, {passive:true}); hero?.addEventListener('touchend', e => { const delta = e.changedTouches[0].screenX - touchStart; if (Math.abs(delta) > 45) showSlide(activeSlide + (delta < 0 ? 1 : -1)); }); startSlider();
const counters = document.querySelectorAll('[data-count]'); const counterObserver = new IntersectionObserver(entries => entries.forEach(entry => { if (!entry.isIntersecting) return; const el = entry.target, end = Number(el.dataset.count), start = performance.now(); const animate = now => { el.textContent = Math.min(end, Math.floor((now - start) / 900 * end)).toLocaleString() + '+'; if (now - start < 900) requestAnimationFrame(animate); }; requestAnimationFrame(animate); counterObserver.unobserve(el); }), {threshold:.5}); counters.forEach(counter => counterObserver.observe(counter));
const testimonials = [...document.querySelectorAll('.testimonial')]; let activeTestimonial = 0; const testimonialPosition = direction => { activeTestimonial = (activeTestimonial + direction + testimonials.length) % testimonials.length; testimonials.forEach((el, i) => el.classList.toggle('is-active', i === activeTestimonial)); document.querySelector('.testimonial-controls span').textContent = `${activeTestimonial + 1} / ${testimonials.length}`; }; document.querySelectorAll('.testimonial-controls button').forEach((button, i) => button.addEventListener('click', () => testimonialPosition(i ? 1 : -1)));
const lightbox = document.querySelector('.lightbox'); document.querySelectorAll('.gallery button').forEach(button => button.addEventListener('click', () => { const source = button.querySelector('img'); lightbox.querySelector('img').src = source.src; lightbox.querySelector('img').alt = source.alt; lightbox.showModal(); })); document.querySelector('.close-lightbox')?.addEventListener('click', () => lightbox.close());
// Keep missing local artwork honest and useful during the demo build.
document.addEventListener('error', event => { const image = event.target; if (image.tagName !== 'IMG' || image.dataset.placeholder) return; image.dataset.placeholder = 'true'; const placeholder = document.createElement('div'); placeholder.className = 'image-placeholder'; placeholder.textContent = image.getAttribute('src').split('/').pop(); image.replaceWith(placeholder); }, true);
document.querySelectorAll('.accordion button').forEach(button => button.addEventListener('click', () => { const panel = button.nextElementSibling; const open = panel.classList.toggle('open'); button.setAttribute('aria-expanded', open); button.querySelector('span').textContent = open ? '−' : '+'; }));
// The contact page loads the Firebase-backed form module only when needed.
if (document.querySelector('.contact-form') && location.pathname.endsWith('/contact.html')) import('./contact-form.js');
if (!document.body.dataset.page && document.querySelector('.news-grid')) import('./home.js');
