/* Public Firestore views. Content is always rendered with textContent. */
import { db } from './firebase.js';
import { collection, getDocs, getDoc, doc, orderBy, query, where, limit } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
import { el, showState, formatDate, submitMessage, text } from './site-data.js';
const page = document.body.dataset.page;
const all = async (name, constraints = []) => { const snap = await getDocs(query(collection(db, name), ...constraints)); return snap.docs.map(d => ({ id:d.id, ...d.data() })); };
const card = (item, type) => { const article=el('article'); if(type==='news'){ if(item.image){const img=document.createElement('img');img.src=`images/${item.image}`;img.alt=text(item.title);img.width=480;img.height=300;img.loading='lazy';article.append(img);} const meta=el('p','news-meta',`${text(item.category)} · ${formatDate(item.date)}`), title=el('h3');const link=el('a','',text(item.title));link.href=`news-detail.html?id=${encodeURIComponent(item.id)}`;title.append(link);article.append(meta,title,el('p','',text(item.summary)));} return article; };
async function news(){const target=document.querySelector('#news-results');showState(target,'Loading news…');try{const records=(await all('news',[orderBy('date','desc')])).sort((a,b)=>new Date(b.date)-new Date(a.date));const filter=document.querySelector('#news-filter'), cats=[...new Set(records.map(x=>text(x.category)))];cats.forEach(c=>{const o=el('option','',c);o.value=c;filter.append(o)});let pageNo=0;const render=()=>{const rows=records.filter(x=>!filter.value||x.category===filter.value), slice=rows.slice(pageNo*6,pageNo*6+6);target.replaceChildren(...(slice.length?slice.map(x=>card(x,'news')):[el('p','data-state','No news matches this category.')]));const nav=document.querySelector('#news-pagination');nav.replaceChildren();for(let i=0;i<Math.ceil(rows.length/6);i++){const b=el('button',i===pageNo?'active':'',String(i+1));b.onclick=()=>{pageNo=i;render()};nav.append(b)}};filter.onchange=()=>{pageNo=0;render()};render();}catch{showState(target,'News is unavailable right now.','error')}}
async function staff(){const target=document.querySelector('#staff-results');showState(target,'Loading staff…');try{const records=await all('staff',[orderBy('name')]), search=document.querySelector('#staff-search'), filter=document.querySelector('#staff-filter');[...new Set(records.map(x=>text(x.faculty)))].forEach(f=>{const o=el('option','',f);o.value=f;filter.append(o)});const render=()=>{const key=search.value.toLowerCase(), rows=records.filter(x=>(!filter.value||x.faculty===filter.value)&&`${x.name} ${x.role} ${x.faculty}`.toLowerCase().includes(key));target.replaceChildren(...(rows.length?rows.map(x=>{const a=el('article','staff-card'), av=el('div','avatar',x.name.split(' ').map(n=>n[0]).join('').slice(0,2));a.append(av,el('h3','',x.name),el('p','',x.role),el('small','',x.faculty),el('p','',x.bio));const b=el('button','button button-navy','Contact');b.onclick=()=>openStaffModal(x);a.append(b);return a;}):[el('p','data-state','No staff members match your search.')]));};search.oninput=render;filter.onchange=render;render();}catch{showState(target,'Staff directory is unavailable right now.','error')}}
function openStaffModal(staff){const modal=document.querySelector('#staff-modal'), form=document.querySelector('#staff-message-form');document.querySelector('#staff-modal-title').textContent=`Contact ${staff.name}`;form.reset();form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('button');b.disabled=true;try{await submitMessage(form,staff.id);form.querySelector('.form-response').textContent='Thank you. Your message has been sent.';}catch(error){form.querySelector('.form-response').textContent=error.message;}finally{b.disabled=false}};modal.showModal();modal.querySelector('.close-lightbox').onclick=()=>modal.close();}
async function calendar(){const target=document.querySelector('#calendar-results');showState(target,'Loading calendar…');try{const records=await all('events',[orderBy('date')]);let date=new Date(2026,9,1);const filter=document.querySelector('#calendar-filter');const render=()=>{const month=date.getMonth(),year=date.getFullYear();document.querySelector('#month-title').textContent=new Intl.DateTimeFormat('en-NG',{month:'long',year:'numeric'}).format(date);const rows=records.filter(x=>{const d=new Date(x.date);return d.getMonth()===month&&d.getFullYear()===year&&(!filter.value||x.category===filter.value)});target.replaceChildren(...(rows.length?rows.map(x=>{const a=el('article','calendar-item');a.append(el('time','',formatDate(x.date)),el('h3','',x.title),el('p','',`${x.time||'Time TBC'} · ${x.category}`),el('p','',x.description));return a;}):[el('p','data-state','No events for this month.')]));};document.querySelector('#previous-month').onclick=()=>{date.setMonth(date.getMonth()-1);render()};document.querySelector('#next-month').onclick=()=>{date.setMonth(date.getMonth()+1);render()};filter.onchange=render;render();}catch{showState(target,'Calendar is unavailable right now.','error')}}
async function detail(){const target=document.querySelector('#article-results'), id=new URLSearchParams(location.search).get('id');if(!id){showState(target,'Article not found.','error');return}showState(target,'Loading article…');try{const snap=await getDoc(doc(db,'news',id));if(!snap.exists()){showState(target,'This article could not be found.','error');return}const n=snap.data();target.replaceChildren(el('p','eyebrow gold-text',`${text(n.category)} · ${formatDate(n.date)}`),el('h1','',n.title),el('p','article-summary',n.summary),el('p','article-body',n.body));}catch{showState(target,'Article is unavailable right now.','error')}}
async function notices(){const target=document.querySelector('#notice-results');showState(target,'Loading notices…');try{const rows=(await all('notices')).filter(x=>x.active!==false);target.replaceChildren(...(rows.length?rows.map(x=>{const a=el('article','notice-card');a.append(el('h2','',x.title),el('p','',x.message));return a;}):[el('p','data-state','There are no active notices.')]));}catch{showState(target,'Notices are unavailable right now.','error')}}
if(page==='news')news();if(page==='staff')staff();if(page==='calendar')calendar();if(page==='news-detail')detail();if(page==='notices')notices();
