import { auth, db } from './firebase.js';
import { onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { collection, doc, getDoc, getDocs, serverTimestamp, setDoc } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
import { getStudentRecord } from './student-role.js';

const profile = document.querySelector('#registration-profile'), statusPanel = document.querySelector('#registration-status'), coursePanel = document.querySelector('#registration-courses'), printPanel = document.querySelector('#registration-print');
let student, user, courses = [], registration, semester = 'First';
const value = item => item === undefined || item === null || item === '' ? '—' : String(item);
const registrationId = () => `${user.uid}_${String(student.session || '').split('/')[0]}_${semester}`;
const relevantCourses = () => courses.filter(course => Number(course.level) === Number(student.level) && course.semester === semester && (course.department === student.department || course.department === 'All')).sort((a,b) => String(a.code || '').localeCompare(String(b.code || '')));
const showProfile = () => { const heading = document.createElement('h2'), details = document.createElement('p'); heading.textContent = 'Registration details'; details.textContent = `${value(student.matricNumber)} · ${value(student.department)} · ${student.level ? `${student.level} Level` : '—'} · ${value(student.session)}`; profile.replaceChildren(heading, details); };
const drawRows = (selected, readonly = false) => {
  const wrap = document.createElement('div'), table = document.createElement('table'), head = document.createElement('thead'), body = document.createElement('tbody'), header = document.createElement('tr'), available = relevantCourses(), availableCodes = new Set(available.map(course => course.code)), byCode = new Map(courses.map(course => [course.code, course])); wrap.className = 'table-wrap'; table.className = 'course-table registration-table'; (readonly ? ['Code','Title','Units','Type'] : ['Select','Code','Title','Units','Type']).forEach(text => { const cell = document.createElement('th'); cell.textContent = text; header.append(cell); }); head.append(header);
  const addRow = (course, removed = false) => { const row = document.createElement('tr'), core = course.type === 'Core'; if (core) row.className = 'is-core'; if (!readonly) { const cell = document.createElement('td'), check = document.createElement('input'); check.type = 'checkbox'; check.value = course.code; check.checked = core || selected.has(course.code); check.disabled = core || removed; check.addEventListener('change', updateSelection); cell.append(check); row.append(cell); } [course.code || '—', removed ? '(course removed)' : value(course.title), removed ? '—' : value(course.units), removed ? '—' : value(course.type)].forEach(item => { const cell = document.createElement('td'); cell.textContent = item; row.append(cell); }); body.append(row); };
  (readonly ? available.filter(course => selected.has(course.code)) : available).forEach(course => addRow(course)); selected.forEach(code => { if (!availableCodes.has(code)) addRow(byCode.get(code) || { code }, !byCode.has(code)); }); table.append(head, body); wrap.append(table); return wrap;
};
const updateSelection = () => { const selected = Array.from(coursePanel.querySelectorAll('input[type="checkbox"]:checked')).map(input => input.value), unitMap = new Map(relevantCourses().map(course => [course.code, Number(course.units) || 0])), total = selected.reduce((sum, code) => sum + (unitMap.get(code) || 0), 0), counter = coursePanel.querySelector('#registration-units'), message = coursePanel.querySelector('#registration-message'), submit = coursePanel.querySelector('#registration-submit'); counter.textContent = `Selected units: ${total} (minimum 15, maximum 24)`; const valid = total >= 15 && total <= 24; counter.className = `registration-units ${valid ? 'is-valid' : 'is-invalid'}`; message.textContent = valid ? '' : total < 15 ? 'Select at least 15 units before submitting.' : 'Select no more than 24 units.'; submit.disabled = !valid; };
const showStatus = () => { statusPanel.replaceChildren(); if (!registration) return; const panel = document.createElement('div'), heading = document.createElement('h3'), message = document.createElement('p'); panel.className = `registration-status status-${registration.status || 'pending'}`; heading.textContent = registration.status === 'approved' ? 'Approved' : registration.status === 'rejected' ? 'Rejected' : 'Pending approval'; message.textContent = registration.status === 'rejected' && registration.remarks ? registration.remarks : registration.status === 'approved' ? 'Your registration has been approved.' : 'Your registration is awaiting approval.'; panel.append(heading, message); statusPanel.append(panel); };
const printRegistration = () => { const selected = new Set(registration.courses || []), total = registration.totalUnits, title = document.createElement('h1'), identity = document.createElement('p'), heading = document.createElement('h2'); printPanel.replaceChildren(); const logo = document.createElement('img'); logo.src = '../images/logo1.png'; logo.alt = 'Ladex International University logo'; logo.width = 52; title.textContent = 'Ladex International University'; heading.textContent = 'Course Registration Form'; identity.textContent = `${value(student.fullName)} · ${value(student.matricNumber)} · ${value(student.department)} · ${value(student.session)} · ${semester} Semester`; printPanel.append(logo, title, heading, identity, drawRows(selected, true)); const totalText = document.createElement('p'), approval = document.createElement('p'); totalText.textContent = `Total units: ${value(total)}`; approval.textContent = `Status: ${value(registration.status)}`; printPanel.append(totalText, approval); window.print(); };
const render = () => { showStatus(); coursePanel.replaceChildren(); const selected = new Set(registration?.courses || []); if (registration?.status === 'approved') { const print = document.createElement('button'), note = document.createElement('p'); note.textContent = 'Your approved registered courses are shown below.'; print.className = 'button button-navy'; print.type = 'button'; print.textContent = 'Print course form'; print.addEventListener('click', printRegistration); coursePanel.append(note, drawRows(selected, true), print); return; } const form = document.createElement('form'), counter = document.createElement('p'), response = document.createElement('p'), submit = document.createElement('button'); form.className = 'registration-card'; counter.id = 'registration-units'; response.id = 'registration-message'; response.className = 'form-response'; response.setAttribute('aria-live','polite'); submit.id = 'registration-submit'; submit.className = 'button button-gold'; submit.type = 'submit'; submit.textContent = registration ? 'Update registration' : 'Submit registration'; form.append(drawRows(selected), counter, response, submit); form.addEventListener('submit', async event => { event.preventDefault(); const selectedCodes = Array.from(form.querySelectorAll('input[type="checkbox"]:checked')).map(input => input.value), unitMap = new Map(relevantCourses().map(course => [course.code, Number(course.units) || 0])), totalUnits = selectedCodes.reduce((sum, code) => sum + (unitMap.get(code) || 0), 0); if (totalUnits < 15 || totalUnits > 24) { updateSelection(); return; } submit.disabled = true; response.textContent = ''; try { await setDoc(doc(db,'registrations',registrationId()),{uid:user.uid,matricNumber:value(student.matricNumber),fullName:value(student.fullName),department:value(student.department),level:Number(student.level),session:value(student.session),semester,courses:selectedCodes,totalUnits,status:'pending',submittedAt:serverTimestamp()}); await loadRegistration(); } catch (error) { console.error('Registration failed:',error.code,error.message); response.textContent = 'Could not save your registration. Please try again.'; } finally { submit.disabled = false; } }); coursePanel.append(form); updateSelection(); };
const loadRegistration = async () => { try { const snapshot = await getDoc(doc(db,'registrations',registrationId())); registration = snapshot.exists() ? snapshot.data() : null; render(); } catch (error) { console.error('Registration failed:',error.code,error.message); coursePanel.textContent = 'Could not load your registration. Please try again.'; } };
const switchSemester = next => { semester = next; document.querySelector('#registration-first').setAttribute('aria-selected',String(next === 'First')); document.querySelector('#registration-second').setAttribute('aria-selected',String(next === 'Second')); loadRegistration(); };
document.querySelector('#registration-first')?.addEventListener('click', () => switchSemester('First'));
document.querySelector('#registration-second')?.addEventListener('click', () => switchSemester('Second'));
onAuthStateChanged(auth, async signedInUser => { if (!signedInUser) { location.href = 'login.html'; return; } user = signedInUser; student = await getStudentRecord(db,user.uid); if (!student) { location.href = 'dashboard.html'; return; } showProfile(); try { const snapshot = await getDocs(collection(db,'courses')); courses = snapshot.docs.map(item => item.data()); await loadRegistration(); } catch (error) { console.error('Registration failed:',error.code,error.message); coursePanel.textContent = 'Courses could not be loaded. Please try again.'; } });
